<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $roles = array(
            'Super Admin' => 1,
            'Human Resources Supervisor' => 1,
            'HR Officer II' => 1,
            'HR Executive Admin' => 1,
            'Human Resource Assistant' => 1,
            'Branch Manager' => 2,
            'Training Coordinator' => 2,
            'Assistant Branch Manager' => 2,
            'Head Barman' => 2,
            'Branch Chef' => 2,
            'Hygiene Manager' => 2,
            'Assistant Branch Chef' => 2,
            'Crew Supervisor' => 2,
            'Senior Barista' => 2,
            'Financial Controller' => 2,
            'Finance Manager-Central Services' => 2,
            'Head of Audit' => 2,
            'Head of Marketing' => 2,
            'Head of Legal' => 2,
            'Head of IT' => 2,
            'Head of Procurement' => 2,
            'Head of Food Safety' => 2,
            'Head of Property / R&M' => 2,
            'Head of FoodScape' => 2,
            'Manufacturing Manager' => 2,
            'Technical Manager' => 2,
            'Sales Manager' => 2,
            'FoodScape Support Service Manager' => 2,
            'General Manager - Java' => 2,
            'Executive Chef Operations' => 2,
            'Operations Manager - Java' => 2,
            'Group Head Barista' => 2,
            'Area Manager' => 2,
            'Regional Chef' => 2,
            'Quality Assurance Supervisor II' => 2,
            'Customer Relations Manager' => 2,
            'Customer Relations Officer' => 2,
            'Stores Supervisor' => 2,
            'Finance Manager - Property & R&M' => 2,
            'Distribution Supervisor' => 2,
            'Regional Internal Auditor' => 2,
            'Logistics & Warehousing Supervisor' => 2,
            'Sales Supervisor' => 2,
            'Finance Manager' => 2,
            'Senior Branch Accountant' => 2,
            'Shift Supervisor - Manufacturing' => 2,
            'Head of Infrastructure' => 2,
            'Quality Assurance Supervisor' => 2,
            'Procurement Manager' => 2,
            'Senior Payables Accountant' => 2,
            'Senior Treasury Accountant' => 2,
            'Senior Controls Accountant' => 2,
            'Commissary Supervisor' => 2,
            'Debtors Controller' => 3,
            'Group Cost Controller' => 3,
            'Cost Controller' => 3,
            'Electrical Technician' => 3,
            'Payroll Accountant' => 3,
            'Statutory Accountant' => 3,
            'Risk Manager' => 3,
            'Audit Supervisor' => 3,
            'Internal Auditor' => 3,
            'Internal Audit Assistant' => 3,
            'Logistics Operator' => 3,
            'General Accountant' => 3,
            'Manufacturing Accountant' => 3,
            'Team Member - Manufacturing (Junior Baker)' => 3,
            'Team Member Bakery (Junior Baker)' => 3,
            'Team Leader - Manufacturing  (Head Baker)' => 3,
            'Team Leader - Manufacturing (Oven Man)' => 3,
            'Team Member - Manufacturing (Baker I)' => 3,
            'Team Member - Manufacturing (Bakery Handy Helper)' => 3,
            'Team Leader - Manufacturing (Assistant Supervisor, Ice Cream)' => 3,
            'Team Member - Manufacturing (Junior Ice Cream Assistant)' => 3,
            'Shift Supervisor - Manufacturing (Assistant Supervisor)' => 3,
            'Team Member - Manufacturing (Packer III)' => 3,
            'Manufacturing Supervisor (Commissary Chef)' => 3,
            'Team Leader - Manufacturing (Roaster)' => 3,
            'Team Leader - Manufacturing (Assistant Commissary Chef)' => 3,
            'Team Member - Manufacturing (Cook II)' => 3,
            'Team Leader - Manufacturing (Cafeteria Cook in Charge)' => 3,
            'Team Member - Hygiene (Commissary Steward)' => 3,
            'Team Leader -Produce (Head of Food Production)' => 3,
            'Team Member - Produce (Food Production Steward)' => 3,
            'Laundry assistant' => 3,
            'Loader' => 3,
            'Receptionist ' => 3,
            'Head of EPOS' => 3,
            'Team Member - Produce (Produce Assistant)' => 3,
            'Line Chef' => 3,
            'Cook II' => 3,
            'Cook I' => 3,
            'Steward' => 3,
            'Barista' => 3,
            'Wait Staff' => 3,
            'Buss Person' => 3,
            'Cashier' => 3,
            'Valet' => 3,
            'Gardener' => 3,
            'Customer Service Associate' => 3,
            'Cook I (Assistant Pizzaiolo)' => 3,
            'Steward (Training in Pasta Making)' => 3,
            'Rider' => 3,
            'Kukito Crew Member' => 3,
            'Barman' => 3,
            'Cook' => 3,
            'Crew Member' => 3,
            'Hostess' => 3,
            'New Product Development Chef' => 3,
            'Multi-Unit Chef (Ug/Rw)' => 3,
            'Guest Relations Officer' => 3,
            'Quality Assurance Supervisor - Foodscape' => 3,
            'Cost Management Accountant - Manufacturing' => 3,
            'Production Accountant' => 3,
            'Stock Control & Compliance Accountant' => 3,
            'Quality Control Team Member' => 3,
            'Hygiene Officer' => 3,
            'Senior Storekeeper' => 3,
            'Verification Officer' => 3,
            'Receiving Officer' => 3,
            'Store keeper & Order Picker Driver' => 3,
            'Maintenance Store keeper' => 3,
            'Store keeper' => 3,
            'Dispatch & Receiving Officer' => 3,
            'Sales Coordinator' => 3,
            'Sales Representative' => 3,
            'Sales Driver' => 3,
            'Merchandiser' => 3,
            'Office Messenger' => 3,
            'Manufacturing Planner' => 3,
            'IT Support Executive' => 3,
            'Hardware Support Technician' => 3,
            'Networks & Security Engineer' => 3,
            'ERP Analyst' => 3,
            'Product Development Technologist' => 3,
            'Legal Assistant' => 3,
            'Procurement Officer' => 3,
            'Service Desk Officer' => 3,
            'Construction Site Engineer' => 3,
            'Senior Maintenance Manager' => 3,
            'Regional Maintenance Manager' => 3,
            'Technician III Refrigeration' => 3,
            'Technician I Refrigeration' => 3,
            'Technician III Electrical' => 3,
            'Technician II Electrical' => 3,
            'Technician I Electrical' => 3,
            'Plumber II' => 3,
            'Plumber I' => 3,
            'Carpenter III' => 3,
            'Carpenter I' => 3,
            'Painter' => 3,
            'Upholster' => 3,
            'Brand Marketer' => 3,
            'Commissary Accountant' => 3,
            'Coffee Sales & Merchandising Representative' => 3,
            'Systems Administrator' => 3,
            'Regional Systems Administrator' => 3,
            'Branch Accountant' => 3,
            'Roaster And Coffee Sales Representative' => 3,
            'Digital Marketer' => 3,
            'Marketing Coordinator' => 3,
            'Senior Regional Accountant' => 3,
            'Finance Receptionist' => 3,
            'Management Accountant' => 3,
        );

        foreach ($roles as $role => $level) {
            $model = new Role();
            $model->name = $role;
            $model->description = 'Give more details on what the ' . $role . ' does within the system.';
            $model->level = $level;
            $model->save();
        }
    }
}
